apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak
  namespace: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/instance: primary
      app.kubernetes.io/name: keycloak
  podMetricsEndpoints:
  - port: "http-envoy-prom"
    path: "/stats/prometheus"
    scheme: "http"
    interval: "15s"
